l_korean:
 DIVISION_QUEUED: "$N$개 사단"
 DIVISIONS_QUEUED: "$N$개 사단"
 CONVEYOR_EQUIPMENT_NEED: "필요 장비:"
 CONVEYOR_MANPOWER_NEED: "필요 인력: $AMOUNT|H$"
 DEPLOYMENT_REQUIREMENT: "$NAME$: $AMOUNT$"
 DEPLOYMENT_DIVISION_LABEL: "사단"
 DEPLOYMENT_PROGRESS_LABEL: "진행도"
 DEPLOYMENT_PRIORITY_LABEL: "우선순위"
 DEPLOYMENT_DEPLOY_LABEL: "배치"
 DEPLOYMENT_TEMPLATE_ITEM_ADD: "§G클릭하여 배치 대기열에 추가§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY: "§G클릭하여 배치 가능 편제 복사§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT: "§G클릭하여 사단 편제 편집§!"
 DEPLOYMENT_TEMPLATE_ITEM_VIEW: "§G클릭하여 사단 편제 보기§!"
 DEPLOYMENT_TRAINING: "훈련: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC: "/ $VALUE|H%0$ (배치 병력의 최대 경험치는 장비의 양에 따라 달라집니다.)"
 DEPLOYMENT_CURRENT_LEVEL: "현재 병력 배치의 수준은 $NUMBER$입니다($LEVEL|%Y0$)"
 DEPLOYMENT_MANPOWER_DESC: "인력: $VALUE|Y0$ (최대 $MAX|Y0$)"
 DEPLOYMENT_EXPERIENCE_DESC: "\n훈련이 완료되면 이 부대는 $NUMBER$단계로 배치될 수 있는 경험치를 획득하며($MAXLEVEL|%Y0$), 전투 변동치 $EFFECT|+=%0$를 얻습니다."
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC: "\n 이 부대가 장비를 완전히 갖췄다면 §Y$DATE$§!에 훈련이 완료됩니다."
 DEPLOYMENT_EQUIPMENT: "장비: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC: "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_DESC: "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_DESIGNER: "사단 설계"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT: "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL: "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EQUIPMENT_CHANGE: "$NAME$: $VALUE$"
 DEPLOYMENT_ADD_TEMPLATE: "훈련"
 DEPLOYMENT_LINES_HIT_THE_CAP: "우리는 인원을 최대 $CAP|*H$만큼 훈련할 수 있습니다.\n배치 가능한 최대 인력에 제한됨($INFIELD|*H$의 $RATIO|H0%$. 최소: $MINPOSSIBLE|*H$명)"
 DEPLOYMENT_LINES_HIT_THE_DIVISION_CAP: "§R이 편제의 상한에 도달함§!\n"
 REGIMENTS_SELECTION_CANCEL: "뒤로"
 ONLY_ONE_TEMPLATE_LEFT: "마지막 남은 편제는 삭제할 수 없습니다."
 DELETE_TEMPLATE: "편제를 목록에서 §R삭제§!합니다."
 DELETE_TEMPLATE_TITLE: "편제 삭제"
 DELETE_TEMPLATE_DESC: "정말로 이 편제를 삭제하시겠습니까?"
 DEPLOYMENT_REMOVE_DIVISION: "사단 취소"
 DEPLOYMENT_DEPLOYMENT_LABEL: "모병 및 배치"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT: "장비가 갖춰지지 않은 부대를 §R배치§!할 수 없습니다.\n장비가 갖춰질 때까지 기다리십시오."
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER: "인력이 없는 부대는 §R배치§!할 수 없습니다."
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING: "$VALUE|1H%$ 이상 훈련되지 않은 부대는 §R배치§!할 수 없습니다(현재 $CURRENT|1R%$)."
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES: "특수부대 한도를 넘기 때문에 부대를 §R배치§!할 수 없습니다."
 DEPLOYMENT_NOT_ALLOWED_REASON_EXCEED_DIVISION_CAP: "사단 편제 한도를 넘기 때문에 부대를 §R배치§!할 수 없습니다."
 DEPLOYMENT_HOW_TO_DESC: "목록에서 배치를 선택한 후 지도에서 강조된 지역을 §G클릭§!하십시오.\n§g장비가 다 갖춰지지 않은 부대는 증원 요청으로 장비를 갖출 것입니다.\n부대를 너무 빨리 배치하면 적절한 훈련을 받지 못한다는 점을 기억하십시오.§!"
 OPERATIONS_DESC: "§Y작전§!\n§T작전 준비 및 실행에 쓰이는 장비의 우선순위를 설정하십시오.§!"
 OPERATIONS_EMPTY: "§G현재 작전을 위한 장비 요청이 없습니다.§!"
 DEPLOYMENT_RAIDS_DESC: "§Y습격§!\n§T습격 준비에 쓰이는 장비의 우선순위를 설정하십시오.§!"
 DEPLOYMENT_RAIDS_EMPTY: "§G현재 습격을 위한 장비 요청이 없습니다.§!"
 REINFORCEMENT: "증원"
 REINFORCEMENT_DESC: "§Y증원§!\n§T장비가 대기열에 있는 부대와 업그레이드, 활동 중인 부대의 증원 중에 어디에 먼저 쓰일지 우선순위를 설정합니다.§!"
 REINFORCEMENT_EMPTY: "§G현재 장비에 대한 요청이 없습니다.§!"
 UPGRADES: "업그레이드"
 UPGRADES_DESC: "§Y업그레이드§!\n§T장비가 배치 대기열과 증원, 활동 중인 부대의 업그레이드 중에 어디에 먼저 쓰일지 우선순위를 설정합니다.§!"
 UPGRADES_EMPTY: "§G현재 업그레이드에 대한 요청이 없습니다.§!"
 group_infantry_title: "보병 대대"
 group_mobile_title: "기동 대대"
 group_armor_title: "기갑 대대"
 group_combat_support_title: "전투 지원 대대"
 group_mobile_combat_support_title: "기동 전투 지원 대대"
 group_armor_combat_support_title: "기갑 전투 지원 대대"
 group_support_title: "지원중대"
 NEW_GROUP_ADDITIONAL_COST: "추가 비용 $VALUE|H0$£army_experience£"
 GARRISONS: "주둔군"
 GARRISONS_DESC: "§Y주둔군§!\n§T주둔군에 쓰이는 장비의 우선순위를 설정합니다.§!"
 GARRISONS_EMPTY: "§G현재 주둔군에 대한 요청이 없습니다.§!"
 TIMED_ACTIVITY_TITLE: "$NAME$(은)는 $COUNTRY$(와)과 적대 중"
 TIMED_ACTIVITY_ALERT_TITLE: "$NAME|H$(은)는 $COUNTRY|H$(와)과 적대 중"
 TIMED_ACTIVITY_ENTRY_DESC: "§T이 외교 활동에 쓰이는 장비의 우선순위를 설정합니다.§!"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC: "§G장비를 최대로 모았습니다.§!"
 LAND_DEPLOYMENT: "§T육군 배치§!"
 AIR_DEPLOYMENT: "§T공군 배치§!"
 NAVAL_DEPLOYMENT: "§T해군 배치§!"
 DIVISION_DESIGNER_RENAME: "이름 변경"
 DIVISION_DESIGNER_UPDATE: "갱신"
 DEPLOY: "배치"
 EDIT: "편집"
 VIEW: "보기"
 COPY: "복사"
 DIVISION_EQUIPMENT: "장비"
 NEW_EQUIPMENT_ALLOWED: "새로운 장비 사용"
 DO_NOT_CONTAINS_TEMPLATE: "§R이 편제는 삭제할 수 없습니다. 국가가 이 편제를 포함하고 있지 않습니다.§!"
 HAS_ARMIES_WITH_TEMPLATE: "§R$AMOUNT|H$개 사단이 이 편제를 사용하고 있어 삭제할 수 없습니다.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE: "§R$AMOUNT|H$개 사단이 이 편제에서 새 편제로 전환 중(새 편제에 맞는 장비가 지급되기를 기다리는 상태)이기에 편제를 삭제할 수 없습니다.§!"
 HAS_EXILE_TRANSFER_WITH_TEMPLATE: "§R망명 중인 $AMOUNT|H$개 사단이 이 편제를 사용하고 있어 삭제할 수 없습니다.§!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE: "$AMOUNT|H$개 배치가 이 편제를 사용하고 있어 국가에서 이 편제를 §R제거§!할 수 없습니다."
 HAS_GARRISON_WITH_TEMPLATE: "§R일부 점령지의 주둔군이 이 편제를 사용하고 있어 삭제할 수 없습니다.§!"
 DEPLOYMENT_TEMPLATE_LABEL: "편제"
 TEMPLATE_PRIO_0: "예비"
 TEMPLATE_PRIO_0_DESC: "이 편제를 사용한 병력은 배치되었을 때 장비를 가장 나중에, 가장 낮은 우선순위로 받습니다. 기지를 지킬 목적 등으로 사용될 병력에 적합합니다."
 TEMPLATE_PRIO_1: "기본"
 TEMPLATE_PRIO_1_DESC: "이 편제를 사용한 병력은 배치되었을 때 장비와 증원을 중간 우선순위로 받습니다."
 TEMPLATE_PRIO_2: "정예"
 TEMPLATE_PRIO_2_DESC: "이 편제를 사용한 병력은 배치되었을 때 장비를 가장 먼저, 가장 높은 우선순위로 받습니다. 정예 부대와 그들이 활약할 수 있는 곳에 적합합니다."
 DEPLOYMENT_LEND_LEASE_COUNTRY: "무기대여: $COUNTRY$"
 ADD_CONVEYOR_LINE_BUTTON_LABEL: "부대 추가"
 ADD_CONVEYOR_LINE_BUTTON_DESC: "병렬로 생산될 $CONVEYOR|H$ 병력을 하나 추가합니다.\n\n§GShift + 클릭§!하면 라인 5개 추가합니다."
 CONVEYOR_GENERIC_NAME_EDIT_DESC: "병력의 일반 이름을 변경하려면 여기에 입력하십시오."
 CONVEYOR_TEMPLATE_ICON_DESC: "이 배치는 $TEMPLATE|H$ 편제를 사용하는 사단을 생성합니다."
 CANCEL_CONVEYOR_TOOLTIP: "모든 배치 라인의 생산을 §R취소§!합니다."
 DEPLOY_CONVEYOR_TOOLTIP: "§G클릭§!하여 모든 라인을 즉시 배치하십시오."
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP: "§R배치§!할 준비가 된 병력이 없습니다."
 CONVEYOR_CANCEL_TITLE: "생산 §R취소§!"
 CONVEYOR_CANCEL_DESC: "정말로 모든 배치 라인의 생산을 §R취소§!하시겠습니까?"
 CONVEYOR_LINE_CANCEL_DESC: "이 라인의 생산을 §R취소§!"
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE: "배치 라인을 §R취소§!"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC: "정말로 이 배치 라인의 생산을 §R취소§!하시겠습니까?\n(배치도 §R제거§!됩니다)"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC: "정말로 이 배치 라인의 생산을 §R취소§!하시겠습니까?"
 CONVEYOR_GROUP_ASSIGN_DESC: "§G클릭§!하여 명령에 배치를 배정합니다.\n§G우클릭§!하여 명령 배정을 초기화합니다."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC: "군에 배치를 배정하려면 전구 내에 하나 이상의 명령이 있어야 합니다."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC: "군에 배치를 배정하려면 목표 장소를 가지고 있어야 합니다."
 CONVEYOR_SET_LOCATION_DESC: "§G클릭§!하여 이 병력의 배치 장소를 지정합니다.\n§G우클릭§!하여 장소를 초기화합니다."
 CONVEYOR_SET_COLONIAL_LOCATION_DESC: "§G클릭§!하여 병력의 배치 장소를 지정합니다.\n§G우클릭§!하여 장소를 초기화합니다.\n§Y식민지 편제의 특성상 원래 국가 안에만 배치할 수 있습니다!§!"
 CONVEYOR_SET_LOCATION_NOT_SET: "§R장소 미설정§!"
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC: "현재 라인의 접두사를 변경하려면 여기에 입력하십시오."
 CONVEYOR_LINE_DEPLOY_DESC: "§G클릭§!하여 이 라인을 즉시 배치합니다."
 CONVEYOR_SERIES_INCREASE_DESC: "각 라인이 완료할 사단의 연속 훈련 횟수를 늘립니다.\n\n무한으로 설정하면 각 라인은 한 사단을 배치한 후 다음 사단을 훈련합니다."
 CONVEYOR_SERIES_AMOUNT_DESC: "각 라인은 사단을 이만큼 훈련한 후 해당 사단을 대기열에서 제거합니다.\n\n무한으로 설정하면 각 라인은 한 사단을 배치한 후 다음 사단을 훈련합니다."
 CONVEYOR_SERIES_DECREASE_DESC: "각 라인이 완료할 사단의 연속 훈련 횟수를 줄입니다.\n\n무한으로 설정하면 각 라인은 한 사단을 배치한 후 새로운 사단을 훈련합니다."
 CONVEYOR_LOW_PRIORITY_DESC: "낮은 증원 우선순위"
 CONVEYOR_MEDIUM_PRIORITY_DESC: "중간 증원 우선순위"
 CONVEYOR_HIGH_PRIORITY_DESC: "높은 증원 우선순위"
 CONVEYOR_CAN_NOT_TRAIN: "§R훈련하는 데 필요한 장비가 부족함§!"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN: "§R훈련하는 데 필요한 인력이 부족함§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT: "§R$DIVS|H$개 사단을 훈련하는 데 필요한 인력이나 장비가 부족함§!"
 CONVEYOR_COLLAPSE_DESC: "§G클릭§!하여 접기"
 CONVEYOR_EXPAND_DESC: "§G클릭§!하여 펼치기"
 CONVEYOR_MOVE_UP: "§G클릭§!하여 위로 올림\n§GShift + 클릭§!하여 제일 위로 올림"
 CONVEYOR_MOVE_DOWN: "§G클릭§!하여 아래로 내림\n§GShift + 클릭§!하여 제일 아래로 내림"
 DEPLOYMENT_LOW_PRIORITY_DESC: "낮은 장비 우선순위"
 DEPLOYMENT_MEDIUM_PRIORITY_DESC: "중간 장비 우선순위"
 DEPLOYMENT_HIGH_PRIORITY_DESC: "높은 장비 우선순위"
 CONVEYOR_HAS_BAD_LOCATION: "목표 장소는 현재 배치하기에 §R부적합§!합니다."
 CONVEYOR_TRAINING_NOT_FINISHED: "이 라인의 훈련이 아직 끝나지 않았습니다."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC: "라인의 현재 연속 훈련 수"
 CONVEYOR_LINE_SERIES_BASE: "$CURRENT$/$TARGET$"
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL: "§H사용자 지정 이름 지우기§!\n이미 사용 중이지 않다면 원래 배정되었던 이름으로 돌아갑니다."
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME: "§H다른 역사적 이름 선택§!\n§G클릭§!하여 아직 사용할 수 있는 모든 역사적 이름이 실린 목록을 엽니다. 편제를 편집하여 이름 모음을 변경할 수 있습니다."
 DEPLOYMENT_LINE_EDIT_NAME: "사용자 지정 이름을 사용하려면 §G클릭§!하고 입력하십시오."
 DEPLOYMENT_LINE_OUT_OF_NAMES: "§g역사적 이름 사용§!"
 MISSING_SPECIAL_FORCES_CAP: "§R특수부대 허용량이 부족함§!"
 EXCEEDING_DIVISION_CAP: "§R사단 편제 상한 초과§!"
 TRAINING_HALTED: "훈련이 중단되었습니다.\n"
 CANNOT_DELETE_SPECIAL_TEMPLATES: "특수 편제를 제거할 수 없습니다."
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS: "새로운 특수 편제 사단을 훈련할 수 없습니다."
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL: "§H망명정부§! 상태에서 새로운 사단을 훈련하려면 §H수도§!를 지배해야 합니다."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP: "특수부대 상한을 초과하게 되므로 이 편제로 변경할 수 없습니다."
 CANT_CHANGE_DUE_TO_DIVISION_CAP: "사단 상한을 초과하게 되므로 이 편제로 변경할 수 없습니다."
 NO_SPECIAL_FORCES: "이 편제는 어떠한 특수부대도 포함하고 있지 않습니다."
 SPECIAL_FORCES_IN_TEMPLATE: "이 편제는 특수부대 수용량을 $NUM|Y$개 사용합니다."
 SPECIAL_FORCES_CAP_DESC: "현재 허용된 특수부대 수용량 $CAP|Y$개 중 $USED|Y$개가 야전에서 활동 중이며 $IN_TRAINING|Y$개가 훈련 중입니다."
 SPECIAL_FORCES_CAP_LIMIT_DESC: "이 사단은 가장 낮은 상한인 특수부대 상한을 사용하고 있습니다."
 DIVISION_CAP_OF_TEMPLATE: "이 편제는 상한이 $NUM|Y$입니다."
 DIVISION_CAP_USAGE_DESC: "현재 $NAME|Y$에 허용된  사단 $CAP|Y$개 중 $USED|Y$개가 야전에서 활동 중이며 $IN_TRAINING|Y$개가 훈련 중입니다."
 DIVISION_CAP_LIMIT_DESC: "이 사단은 가장 낮은 상한인 편제 상한을 사용하고 있습니다."
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE: "이로써 이 편제를 사용하는 사단을  $TRAINABLE|Y$개 더 훈련할 수 있습니다."
 SHOW_DECOMMISSIONED_TEMPLATES: "§H퇴역된 편제§! 보기"
 DECOMMISSION_TEMPLATE_TOGGLE_ON: "퇴역"
 DECOMMISSION_TEMPLATE_TOGGLE_ON_DESC: "§G클릭§!하여 해당 사단 편제를 퇴역시킵니다."
 DECOMMISSION_TEMPLATE_TOGGLE_OFF: "재취역"
 DECOMMISSION_TEMPLATE_TOGGLE_OFF_DESC: "§G클릭§!하여 해당 사단 편제를 재취역시킵니다."
 DEPLOYMENT_VIEW_SPECIAL_FORCES_DETAILS: "$USED$/$CAP$"
